name: voice_translate
description: Offline voice translation app (VI EN)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  record: ^6.0.0
  path_provider: ^2.1.2
  flutter_tts: ^4.0.2
  permission_handler: ^11.3.0
  get_it: ^7.7.0
  logger: ^2.3.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/models/ggml-base.bin
    - assets/models/gemma-2b-it-cpu-int4.bin

